stock:
  token: pF35gakJH3T9WgcIoe5i8s98AxrCIgQECTwXR0NP
  url:
    quote: https://api.stockdata.org/v1/data/quote?symbols=%s&api_token=%s
    historical-quote: https://api.stockdata.org/v1/data/eod/multiple?symbols=%s&date=%s&api_token=%s
server:
  port: 8010

spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/account
    username: account
    password: account
  jpa:
    show-sql: true

security:
  jwt:
    expiration: 600
    secret: c2VjcmV0